### ISSUE TITLE
VS2015编译不通过

### ISSUE THREAD

**Issue by dashenxiwo** [yuanyuanxiang/SimpleRemoter#10]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误(活动)		CList 不是模板	Yama server\2015Remote\IOCPServer.h	  50	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1071	在注释中遇到意外的文件结束 (编译源文件 2015RemoteDlg.cpp)	Yama server\2015remote\gh0st2remote.h	33	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	C1071	在注释中遇到意外的文件结束 (编译源文件 FileManagerDlg.cpp)	Yama server\2015remote\gh0st2remote.h	33

**Comment by yuanyuanxiang** [comment]
> 严重性 代码 说明 项目 文件 行 禁止显示状态
> 错误(活动) CList 不是模板 Yama server\2015Remote\IOCPServer.h 50
> 
> 严重性 代码 说明 项目 文件 行 禁止显示状态
> 错误 C1071 在注释中遇到意外的文件结束 (编译源文件 2015RemoteDlg.cpp) Yama server\2015remote\gh0st2remote.h 33
> 
> 严重性 代码 说明 项目 文件 行 禁止显示状态
> 错误 C1071 在注释中遇到意外的文件结束 (编译源文件 FileManagerDlg.cpp) Yama server\2015remote\gh0st2remote.h 33

请升级代码到最新再试。另外代码并无问题，这可能是VS2015的问题，请搜索寻找可能的解决办法。对于“错误 C1071”，请把gh0st2remote.h第33行的注释删掉。

**Comment by yuanyuanxiang** [comment]
该项目已升级编译器为VS2019: https://github.com/yuanyuanxiang/SimpleRemoter/commit/0d6c64f87b8ae50d1ccf6776ad4e533c64635c0c

如果需要所编译的程序能在XP系统运行，则需要VS2017及以前版本的编译器。鉴于本人精力有限，不再处理有关VS2019以前编译器的问题。
