### ISSUE TITLE
用私钥登陆vps，就无法登陆，提示如下错误

### ISSUE THREAD

**Issue by star2k** [yuanyuanxiang/SimpleRemoter#14]
![](http://star2k10.3322.org:888/imgs/2021/11/2775ab8ed91f24e1.png)
![](http://star2k10.3322.org:888/imgs/2021/11/8b8ba7cd3cd07a52.png)
![](http://star2k10.3322.org:888/imgs/2021/11/5d4b6bdb833cc645.png)

**Comment by yuanyuanxiang** [comment]
提供的信息不足，无法解决问题! 如还需帮助，请重新打开问题，并附上更多信息。
