### ISSUE TITLE
注册表管理无法编辑

### ISSUE THREAD

**Issue by gls1018** [yuanyuanxiang/SimpleRemoter#18]
使用注册表管理, 只能查看远程电脑的注册表, 无法去修改它

**Comment by yuanyuanxiang** [comment]
问题已获悉，感谢反馈！待我有空的时候看一下这个问题，尝试修复。
如果大家有谁能提供修复代码进行合并，那自然是极好的。

**Comment by yuanyuanxiang** [comment]
暂不具备编辑注册表的功能。
