### ISSUE TITLE
fatal error C1083: 无法打开包括文件: “vld.h”: No such file or directory 

### ISSUE THREAD

**Issue by wqvbjhc** [yuanyuanxiang/SimpleRemoter#2]
1.SimpleRemoter-1.0.0.4编译不了，错误如下。客户端与服务器都有这个错误。
fatal error C1083: 无法打开包括文件: “vld.h”: No such file or directory 
2.客户端ClientDll.sln打开后里面只有一个工程ServerDll. 但我看客户端的目录里有ClientDll.vcxproj，ghost.vcxproj，TestRun.vcxproj三个工程文件。这些工程文件需要吗？

**Comment by yuanyuanxiang** [comment]
1、vld.h文件是Visual Leak Detector工具提供的，用于检测内存泄漏，如果没有安装此工具，请注释该行即可；
2、你可以单独打开"vcxproj"文件，或者，建议您打开2015Remote.sln工程文件。

**Comment by yuanyuanxiang** [comment]
按照上述操作即可解决此问题。
