### ISSUE TITLE
文件管理功能存在偶发崩溃的缺陷

### ISSUE THREAD

**Issue by a3396616601** [yuanyuanxiang/SimpleRemoter#3]
我在研究修复更新这个文件管理功能。谢谢

**Comment by yuanyuanxiang** [comment]
@a3396616601 我尝试修复过“多次打开文件管理窗口会崩溃”的缺陷（将某些Windows函数返回值改为static变量，因为它原本返回的就是static变量），但只是略有改善；多次打开该窗口仍然会随机崩溃，故已将该功能暂停使用。我本人目前没有解决思路，如果你有思路，不妨拿出来讨论。

**Comment by wrkamvip** [comment]
@yuanyuanxiang 能把原来有的那个URL 动态域名方式修复么，没动态域名只能局域网 或者有固定IP才能用哦

**Comment by yuanyuanxiang** [comment]
@wrkamvip 我不是专门研究远程控制方面的人，现从事于九九六，较少有时间修复此功能。需要您自己研究并修复该功能。

**Comment by ZhengJian1996** [comment]
远程文件功能没法使用，发现FileManager里面的void OnReceive(LPBYTE lpBuffer, UINT nSize);跟基类里面
	VOID OnReceive(PBYTE szBuffer, ULONG ulLength);不一样。是故意这么做的吗

**Comment by tin7safe** [comment]
有点意思，这个文件管理功能，作者是不想修复了吗？

**Comment by yuanyuanxiang** [comment]
@ZhengJian1996 我也是才发现子类该方法的第2个参数和基类的不一样。你不妨试试改为一样再编译程序。

**Comment by yuanyuanxiang** [comment]
@tin7safe 近期没有资源修复该bug。

**Comment by haoqing1314** [comment]
文件管理不能用，希望能加入个上传或下载文件

**Comment by c0asters** [comment]
希望继续更新，修复！
