### ISSUE TITLE
动态域名

### ISSUE THREAD

**Issue by wrkamvip** [yuanyuanxiang/SimpleRemoter#4]
能把原来GH0ST客户端有的那个URL 动态域名方式修复么，没动态域名只能局域网 或者有固定IP才能用哦

**Comment by wrkamvip** [comment]
动态域名倒是解决了  好像在WIN10企业版下面 好像远程桌面黑屏不显示图像噢

**Comment by yuanyuanxiang** [comment]
@wrkamvip 是否远程机器没有显示器或者显示器没有打开？

**Comment by wrkamvip** [comment]
都有  我mstsc练上去的话这个远控又可以看到画面不能操控

**Comment by yuanyuanxiang** [comment]
@wrkamvip 是的，若mstsc到远程机器，则远程有画面。我怀疑是和CPU有关，有的CPU自带GPU功能则远程有画面，有的CPU则远程黑屏，但mstsc连接之后有画面。

**Comment by yuanyuanxiang** [comment]
从 [e234b37](https://github.com/yuanyuanxiang/SimpleRemoter/commit/e234b372794e4bcfecf10813b33397734111d91a) 开始，已支持对域名的解析。如果传入的参数第一个字符非数字，则会先进行域名解析。因此，此问题被关闭。
