### ISSUE TITLE
最新版本生成的客户端无法打开！

### ISSUE THREAD

**Issue by woOzZ2** [yuanyuanxiang/SimpleRemoter#8]
始终提示“此电脑无法在你的电脑上运行” windows 7也不行

**Comment by yuanyuanxiang** [comment]
@ss6916 你说的是client代码生成的被控端程序吗？如果是，请检查一下是否被杀毒软件拦截了。

**Comment by woOzZ2** [comment]
> @ ss6916你说的是客户端代码生成的被控端程序吗？如果是，请检查一下是否被杀毒软件拦截了。

@yuanyuanxiang 是的。虚拟机和物理机，win7/10 ，win10关闭windows defeder win7没装杀软。重复从你github上下载编译好的版本，始终提示无法运行，无法运行的程序是Yama.exe开启后单击“生成客户端”后的ClientDemo.exe文件，至始至终uoji终都无法运行。。。。。。
你可以试一下。。。。

**Comment by yuanyuanxiang** [comment]
@ss6916 我在Release页面下载的"v1.0.0.5.zip"包，用里面的主控端生成的ClientDemo.EXE确实存在你说的问题；但是我用Visual Studio 2015重新编译的主控端没有这个问题。我在Win7旗舰版 64位虚拟机测试。

**Comment by woOzZ2** [comment]
@yuanyuanxiang 是的，后来我使用Visual Studio 2015编译后就能生成了，但是文件和语音不能使用，并且Visual Studio 2019无法编译

**Comment by xixuedafa** [comment]
vs2019要把编译的参数改了sdk 8.1改了，还有就是vs2015改了，再注释或者安装vld就能通过，网上都能搜到。

**Comment by kuA35sSaasd** [comment]
> @ss6916 我在Release页面下载的"v1.0.0.5.zip"包，用里面的主控端生成的ClientDemo.EXE确实存在你说的问题；但是我用Visual Studio 2015重新编译的主控端没有这个问题。我在Win7旗舰版 64位虚拟机测试。

能重新上传下么。。。现在依然有这个问题

**Comment by yuanyuanxiang** [comment]
已升级IDE为VS2019，详见：https://github.com/yuanyuanxiang/SimpleRemoter/commit/0d6c64f87b8ae50d1ccf6776ad4e533c64635c0c

另外，我亲自测试了最新版本生成的客户端在Win7可以打开。注意升级到VS2019后，所编译的程序将无法在XP运行。

综上所述，这个问题可以关闭了。
