### ISSUE TITLE
CKernelManager::~CKernelManager()

### ISSUE THREAD

**Issue by boyang987** [yuanyuanxiang/SimpleRemoter#9]
CKernelManager::~CKernelManager()
{
	printf("~CKernelManager begin\n");
	int i = 0;
	for (i=0;i<0x1000;++i)
	{
		if (m_hThread->h!=0)
		{
			CloseHandle(m_hThread[i].h);
			m_hThread[i].h = NULL;
			m_hThread[i].run = FALSE;
			while (m_hThread[i].p)
				Sleep(50);
		}
	}
	m_ulThreadCount = 0;
	printf("~CKernelManager end\n");
}

**Comment by boyang987** [comment]
if (m_hThread->h!=0)  ,error

**Comment by boyang987** [comment]
-->if( m_hThread[i].h != 0)

**Comment by yuanyuanxiang** [comment]
> -->if( m_hThread[i].h != 0)

这里确实存在问题，应该按你的建议修改。
